import Page from "components/Page";

const faqs = [
  {
    title: <p>What is Ethentic?</p>,
    answer: (
      <p>
        Ethentic combines the anticipation and excitement of on-chain generative art with the
        physical presence of 3D-printable objects. Ethentic NFTs are generated at time of mint,
        including the 3D-printable model and some gorgeous renders of it.
      </p>
    ),
    id: 1
  },
  {
    title: <p>How is it unique?</p>,
    answer: (
      <p>
        Most generative NFT projects provide a digital representation of the art in a common image
        format. Ethentic goes beyond this by providing a 3D-printable format that can be used to
        display your art in physical form. Ethentic is a first-in-class project using on-chain
        algorithms and traits to generate 3D-printable art. In addition to the novelties of the
        artwork, there are innovations in the smart contracts discussed further below.
      </p>
    ),
    id: 2
  },
  {
    title: <p>How Are Ethentic NFTs Generated?</p>,
    answer: (
      <p>
        Ethentic NFTs are generated procedually using the OpenSCAD programming language. The
        on-chain scripts and traits are combined to generate 3D models with varying characteristics.
        The digital images associated with each NFT are created by feeding the STL model into a
        Blender script and rendering the scene to a PNG.
      </p>
    ),
    id: 3
  },
  {
    title: <p>...Wait, There is a physical copy?</p>,
    answer: (
      <p>
        Yes, owners can redeem and receive the first edition print of their Ethentic NFT delivered
        for a cost. Note that, due to intervening governments, there are some countries to which we
        are just not physically able to ship. Thankfully the STL file is always generatable or
        downloadable through the token owner portal, no matter what borders try to divide us.
      </p>
    ),
    id: 4
  },
  {
    title: <p>Are the NFT traits unique?</p>,
    answer: (
      <p>
        Yes, because of the{" "}
        <a
          className="text-red-600 font-semibold"
          href="https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle"
          target="_blank"
          rel="noopener noreferrer">
          Sparse Fisher-Yates algorithm
        </a>{" "}
        and{" "}
        <a
          className="text-red-600 font-semibold"
          href="http://phrogz.net/lazy-cartesian-product"
          target="_blank"
          rel="noopener noreferrer">
          Lazy Cartesian product
        </a>{" "}
        implemented in the Ethentic smart contract, no set of traits can be chosen twice. Moreover,
        the traits for Ethentic pieces are on-chain unlike most other projects in the space.
      </p>
    ),
    id: 5
  },
  {
    title: <p>Why all this "on-chain" talk?</p>,
    answer: (
      <p>
        The innovation of smart contracts enables us to interact in unstoppable ways. Ethentic takes
        advantage of Ethereum's data storage capabilities to ensure that the art pieces can never
        disappear. By having the seed, traits, and art algorithm stored on-chain, anyone can render
        the art out in its 3D form and bring it to life. No matter what happens to servers, IPFS
        pinning services, or anything of the sort, Ethentic art pieces will always be available.
      </p>
    ),
    id: 6
  },
  {
    title: <p>Are the NFT traits random?</p>,
    answer: (
      <p>
        The NFT traits are randomly selected at each mint from the set of unchosen trait sets (see
        uniqueness section above).
      </p>
    ),
    id: 7
  },
  {
    title: <p>When will the mint go live?</p>,
    answer: <p>The Causeways sale will go live on July 14, 2022 at 12:30pm UTC.</p>,
    id: 8
  },
  {
    title: <p>Will some NFTs be rarer than others?</p>,
    answer: (
      <p>
        Of course! However, the actual composition of the collection - and subsequently the "rarer"
        traits of the collection - will not be determined until after the sale has been completed.
        For example, if a collection has a total of 5 traits, and the available combinations of all
        these traits is roughly 15,000, only a small subset of these possible combinations will
        actually be minted during the sale. Not even the Ethentic team can know which traits will be
        rarer than others; this will be randomly determined at the time of mint.
      </p>
    ),
    id: 9
  },
  {
    title: <p>What do I own when I own an Ethentic piece?</p>,
    answer: (
      <p>
        The unique ownership association on-chain is between your address and the seed and traits
        stored at mint. The STL (3D model) is provided on the Ethentic website as a convenience, but
        it can be generated by you or anyone else since the algorithm is itself stored on-chain as
        well. Finally, the image renders of the NFT are provided as a convenience and beautifying
        layer in your token owner portal on the Ethentic website.
      </p>
    ),
    id: 10
  },
  {
    title: <p>What benefits does my Ethentic NFT grant me?</p>,
    answer: (
      <p>
        Those who purchase at least one of The Causeways NFTs will join NILON. Members will gain
        exclusive rights (e.g., mints, early access, membership cards, etc.) and access to the NILON
        channel in the Ethentic discord. This channel is where future lore and projects on the
        Ethentic platform are being developed. We will work with our community to develop the story
        behind Ethentic, as well as research new forms of algorithmically-generated 3D art inspired
        by the natural world. Those in NILON will join us on the ground level and take part in the
        future of the Ethentic project.
      </p>
    ),
    id: 11
  }
];

export default function About() {
  return (
    <Page className="font-mono">
      <div className="relative bg-red-800 font-mono py-0 md:py-24 lg:py-32">
        <div className="absolute inset-0">
          <img className=" w-full h-full object-cover" src="../images/showroom.png" alt="" />
          <div className="absolute inset-0 bg-teal-100 mix-blend-multiply" aria-hidden="true" />
        </div>
        <div className="relative max-w-7xl mx-auto py-24 px-4 sm:py-32 sm:px-6 lg:px-8">
          <h1 className="text-xl md:text-5xl font-bold tracking-tight text-white sm:text-5xl lg:text-6xl">
            About Ethentic
          </h1>
          <p className="mt-6 text-lg md:text-4xl text-white max-w-3xl">Questions and Answers.</p>
        </div>
      </div>

      <div className="py-8 xl:py-12 px-4 sm:px-6 lg:px-4 bg-teal-500 lg:grid lg:grid-cols-1  lg:space-y-0 justify-items-center">
        {faqs.map((question) => (
          <div key={question.id} className="max-w-max lg:max-w-7xl mx-auto ">
            <div className="relative z-10  md:px-6 ">
              <div className="text-base  max-w-prose">
                <div className="text-xl font-bold tracking-tight sm:text-xl text-white font-mono">
                  {question.title}
                </div>
              </div>
            </div>

            <div className="relative mb-6 max-w-prose">
              <div className="relative  md:p-6">
                <div className="lg:grid lg:grid-cols-1 lg:gap-6">
                  <div className="mt-2 text-md md:text-lg text-teal-800 font-medium font-mono">
                    <div>{question.answer}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="bg-teal-700">
        <div className="max-w-2xl mx-auto text-center py-16 px-4 sm:py-20 sm:px-6 lg:px-8 font-mono">
          <h2 className="text-3xl font-extrabold text-white sm:text-4xl">
            <span className="block">Piqued your interest?</span>
            <span className="block mt-4 ml-5">Explore the Causeways.</span>
          </h2>
          <a
            href="/collections"
            className="mt-8 w-full inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-teal-600 bg-white hover:bg-teal-50 sm:w-auto">
            Browse collection
          </a>
          {/* TODO: Add buy now button */}
        </div>
      </div>
    </Page>
  );
}
